# Generated by Django 4.1.1 on 2022-09-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guestnotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('note', models.TextField()),
                ('like_tiangolo', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('python', 'python'), ('not_python', 'not python'), ('not_not_python', 'not python (php)')], default='python', max_length=100)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
