# Generated by Django 4.1.1 on 2022-09-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guestnotes',
            new_name='Guestnote',
        ),
    ]
