openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /guestnotes/:
    get:
      operationId: listguestnote_lists
      description: List all guest notes, or create a new guest note
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - guestnotes
    post:
      operationId: createguestnote_list
      description: List all guest notes, or create a new guest note
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - guestnotes
  /guestnotes{format}:
    get:
      operationId: retrieveguestnote_list
      description: List all guest notes, or create a new guest note
      parameters:
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - guestnotes{format}
    post:
      operationId: createguestnote_list
      description: List all guest notes, or create a new guest note
      parameters:
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - guestnotes{format}
  /guestnotes/{id}/:
    get:
      operationId: retrieveguestnote_detail
      description: Retrieve, update or delete a guest note.
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - guestnotes
    put:
      operationId: updateguestnote_detail
      description: Retrieve, update or delete a guest note.
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - guestnotes
    delete:
      operationId: destroyguestnote_detail
      description: Retrieve, update or delete a guest note.
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - guestnotes
  /guestnotes/{id}{format}:
    get:
      operationId: retrieveguestnote_detail
      description: Retrieve, update or delete a guest note.
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - guestnotes
    put:
      operationId: updateguestnote_detail
      description: Retrieve, update or delete a guest note.
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - guestnotes
    delete:
      operationId: destroyguestnote_detail
      description: Retrieve, update or delete a guest note.
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - guestnotes
