# use this docker-compose file to simulate a staging environment
# docker-compose -f docker-compose.prod.yml up --build
version: "3.9"
services:
  #Django service
  django:
    build:
      context: ./
      dockerfile: docker/Dockerfile.prod
    ports:
      - 8000:8000
    restart: on-failure
    environment:
      SECRET_KEY: ${DJANGO_SECRET_KEY}
